### ISSUE TITLE
web sdk does not work with angular 10

### ISSUE THREAD

**Issue by uzairzaffar** [adjust/web_sdk#24]
I have been trying to integrate adjust sdk with our application, We are currently using angular 10. on given resources I am unable to find any resource that enable to integrate with typed interfaces.

 

I have come across https://github.com/adjust/web_sdk for web integration however upon including this sdk I am getting following errors.

 

 

Error: node_modules/@adjustcom/adjust-web-sdk/dist/adjust-latest.d.ts:159:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

 

159 function initSdk({ logLevel, logOutput, ...options }: InitOptions): void

    ~~~~~~~~

 

 

Error: node_modules/@adjustcom/adjust-web-sdk/dist/adjust-latest.d.ts:327:16 - error TS1254: A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.

 

327 const Adjust = {

                   ~

328   initSdk,

    ~~~~~~~~~~

...

342   initSmartBanner,

    ~~~~~~~~~~~~~~~~~~

343 }

**Comment by YaroslavnaMatkova** [comment]
Hi @uzairzaffar! Thank you for your report.

A new version [v5.2.1](https://github.com/adjust/web_sdk/releases/tag/v5.2.1) was just released and it should hopefully address this issue. If you can give it a try and let us know if the issue is still out there or if it's gone, would be great. Thank you in advance!

**Comment by uzairzaffar** [comment]
@YaroslavnaMatkova 
I am able to initialize app but getting this error
[adjust-sdk] 2021-09-17T09:39:06.281Z LOG:   Running track event is delayed until Adjust SDK is up

**Comment by YaroslavnaMatkova** [comment]
This message means the SDK wasn't able to send `/session` request or got a response containing an error.

The getting successful response on first `/session` request is considering as an install in Web, and it's not possible to track events until install happen because the backend declines these events anyway. Those events aren't lost but being preserved until installation happen.

The most common reason the SDK requests are being rejected by advertisement blocking software like AdBlock browser extension. 

Could you please share the full console log from browser dev tools?

**Comment by uzairzaffar** [comment]
I was able to make /session request however getting this error message in response to https://app.adjust.com/session 

{"timestamp":"2021-09-17T10:59:13.366Z+0000","message":"Session failed (tracking disabled) (app_token:**********) (platform:web)","error":"Session failed (tracking disabled) (app_token::**********) (platform:web)"}

**Comment by YaroslavnaMatkova** [comment]
Seems web platform tracking is disabled for your app. You would need to contact your Adjust Account Manager or Customer Success Manager so that they can enable Web Tracking for you.
